//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessHacker.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int RefreshInterval {
            get {
                return ((int)(this["RefreshInterval"]));
            }
            set {
                this["RefreshInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("820, 549")]
        public global::System.Drawing.Size WindowSize {
            get {
                return ((global::System.Drawing.Size)(this["WindowSize"]));
            }
            set {
                this["WindowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200, 200")]
        public global::System.Drawing.Point WindowLocation {
            get {
                return ((global::System.Drawing.Point)(this["WindowLocation"]));
            }
            set {
                this["WindowLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("355")]
        public int SplitterDistance {
            get {
                return ((int)(this["SplitterDistance"]));
            }
            set {
                this["SplitterDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState WindowState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["WindowState"]));
            }
            set {
                this["WindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DebugMem {
            get {
                return ((bool)(this["DebugMem"]));
            }
            set {
                this["DebugMem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("&String Scan...")]
        public string SearchType {
            get {
                return ((string)(this["SearchType"]));
            }
            set {
                this["SearchType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowAccountDomains {
            get {
                return ((bool)(this["ShowAccountDomains"]));
            }
            set {
                this["ShowAccountDomains"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WarnDangerous {
            get {
                return ((bool)(this["WarnDangerous"]));
            }
            set {
                this["WarnDangerous"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ProcessTreeColumns {
            get {
                return ((string)(this["ProcessTreeColumns"]));
            }
            set {
                this["ProcessTreeColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ThreadListViewColumns {
            get {
                return ((string)(this["ThreadListViewColumns"]));
            }
            set {
                this["ThreadListViewColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("504, 482")]
        public global::System.Drawing.Size ResultsWindowSize {
            get {
                return ((global::System.Drawing.Size)(this["ResultsWindowSize"]));
            }
            set {
                this["ResultsWindowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ModuleListViewColumns {
            get {
                return ((string)(this["ModuleListViewColumns"]));
            }
            set {
                this["ModuleListViewColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MemoryListViewColumns {
            get {
                return ((string)(this["MemoryListViewColumns"]));
            }
            set {
                this["MemoryListViewColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("791, 503")]
        public global::System.Drawing.Size MemoryWindowSize {
            get {
                return ((global::System.Drawing.Size)(this["MemoryWindowSize"]));
            }
            set {
                this["MemoryWindowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ResultsListViewColumns {
            get {
                return ((string)(this["ResultsListViewColumns"]));
            }
            set {
                this["ResultsListViewColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tabGeneral")]
        public string ProcessWindowSelectedTab {
            get {
                return ((string)(this["ProcessWindowSelectedTab"]));
            }
            set {
                this["ProcessWindowSelectedTab"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PrivilegeListColumns {
            get {
                return ((string)(this["PrivilegeListColumns"]));
            }
            set {
                this["PrivilegeListColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GroupListColumns {
            get {
                return ((string)(this["GroupListColumns"]));
            }
            set {
                this["GroupListColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("481, 468")]
        public global::System.Drawing.Size TokenWindowSize {
            get {
                return ((global::System.Drawing.Size)(this["TokenWindowSize"]));
            }
            set {
                this["TokenWindowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("439, 413")]
        public global::System.Drawing.Size PEWindowSize {
            get {
                return ((global::System.Drawing.Size)(this["PEWindowSize"]));
            }
            set {
                this["PEWindowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PECOFFHColumns {
            get {
                return ((string)(this["PECOFFHColumns"]));
            }
            set {
                this["PECOFFHColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PECOFFOHColumns {
            get {
                return ((string)(this["PECOFFOHColumns"]));
            }
            set {
                this["PECOFFOHColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PEImageDataColumns {
            get {
                return ((string)(this["PEImageDataColumns"]));
            }
            set {
                this["PEImageDataColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PESectionsColumns {
            get {
                return ((string)(this["PESectionsColumns"]));
            }
            set {
                this["PESectionsColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PEExportsColumns {
            get {
                return ((string)(this["PEExportsColumns"]));
            }
            set {
                this["PEExportsColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PEImportsColumns {
            get {
                return ((string)(this["PEImportsColumns"]));
            }
            set {
                this["PEImportsColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.google.com/search?q=%s")]
        public string SearchEngine {
            get {
                return ((string)(this["SearchEngine"]));
            }
            set {
                this["SearchEngine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Chartreuse")]
        public global::System.Drawing.Color ColorNewProcesses {
            get {
                return ((global::System.Drawing.Color)(this["ColorNewProcesses"]));
            }
            set {
                this["ColorNewProcesses"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 60, 40")]
        public global::System.Drawing.Color ColorRemovedProcesses {
            get {
                return ((global::System.Drawing.Color)(this["ColorRemovedProcesses"]));
            }
            set {
                this["ColorRemovedProcesses"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 255, 170")]
        public global::System.Drawing.Color ColorOwnProcesses {
            get {
                return ((global::System.Drawing.Color)(this["ColorOwnProcesses"]));
            }
            set {
                this["ColorOwnProcesses"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 170, 102")]
        public global::System.Drawing.Color ColorElevatedProcesses {
            get {
                return ((global::System.Drawing.Color)(this["ColorElevatedProcesses"]));
            }
            set {
                this["ColorElevatedProcesses"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("170, 204, 255")]
        public global::System.Drawing.Color ColorSystemProcesses {
            get {
                return ((global::System.Drawing.Color)(this["ColorSystemProcesses"]));
            }
            set {
                this["ColorSystemProcesses"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int HighlightingDuration {
            get {
                return ((int)(this["HighlightingDuration"]));
            }
            set {
                this["HighlightingDuration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AlwaysOnTop {
            get {
                return ((bool)(this["AlwaysOnTop"]));
            }
            set {
                this["AlwaysOnTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("415, 503")]
        public global::System.Drawing.Size ThreadWindowSize {
            get {
                return ((global::System.Drawing.Size)(this["ThreadWindowSize"]));
            }
            set {
                this["ThreadWindowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CallStackColumns {
            get {
                return ((string)(this["CallStackColumns"]));
            }
            set {
                this["CallStackColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseToolhelpModules {
            get {
                return ((bool)(this["UseToolhelpModules"]));
            }
            set {
                this["UseToolhelpModules"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NewProcesses {
            get {
                return ((bool)(this["NewProcesses"]));
            }
            set {
                this["NewProcesses"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TerminatedProcesses {
            get {
                return ((bool)(this["TerminatedProcesses"]));
            }
            set {
                this["TerminatedProcesses"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool NewServices {
            get {
                return ((bool)(this["NewServices"]));
            }
            set {
                this["NewServices"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool StartedServices {
            get {
                return ((bool)(this["StartedServices"]));
            }
            set {
                this["StartedServices"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool StoppedServices {
            get {
                return ((bool)(this["StoppedServices"]));
            }
            set {
                this["StoppedServices"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DeletedServices {
            get {
                return ((bool)(this["DeletedServices"]));
            }
            set {
                this["DeletedServices"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowIcon {
            get {
                return ((bool)(this["ShowIcon"]));
            }
            set {
                this["ShowIcon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ServiceListViewColumns {
            get {
                return ((string)(this["ServiceListViewColumns"]));
            }
            set {
                this["ServiceListViewColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HandleListViewColumns {
            get {
                return ((string)(this["HandleListViewColumns"]));
            }
            set {
                this["HandleListViewColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FilterHandleListViewColumns {
            get {
                return ((string)(this["FilterHandleListViewColumns"]));
            }
            set {
                this["FilterHandleListViewColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("554, 463")]
        public global::System.Drawing.Size FilterHandleWindowSize {
            get {
                return ((global::System.Drawing.Size)(this["FilterHandleWindowSize"]));
            }
            set {
                this["FilterHandleWindowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("204, 187, 255")]
        public global::System.Drawing.Color ColorBeingDebugged {
            get {
                return ((global::System.Drawing.Color)(this["ColorBeingDebugged"]));
            }
            set {
                this["ColorBeingDebugged"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("204, 255, 255")]
        public global::System.Drawing.Color ColorServiceProcesses {
            get {
                return ((global::System.Drawing.Color)(this["ColorServiceProcesses"]));
            }
            set {
                this["ColorServiceProcesses"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PromptBoxText {
            get {
                return ((string)(this["PromptBoxText"]));
            }
            set {
                this["PromptBoxText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RunAsUsername {
            get {
                return ((string)(this["RunAsUsername"]));
            }
            set {
                this["RunAsUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RunAsCommand {
            get {
                return ((string)(this["RunAsCommand"]));
            }
            set {
                this["RunAsCommand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tabPrivileges")]
        public string TokenWindowTab {
            get {
                return ((string)(this["TokenWindowTab"]));
            }
            set {
                this["TokenWindowTab"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HideWhenMinimized {
            get {
                return ((bool)(this["HideWhenMinimized"]));
            }
            set {
                this["HideWhenMinimized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("493, 465")]
        public global::System.Drawing.Size ProcessWindowSize {
            get {
                return ((global::System.Drawing.Size)(this["ProcessWindowSize"]));
            }
            set {
                this["ProcessWindowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PlotterAntialias {
            get {
                return ((bool)(this["PlotterAntialias"]));
            }
            set {
                this["PlotterAntialias"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lime")]
        public global::System.Drawing.Color PlotterCPUKernelColor {
            get {
                return ((global::System.Drawing.Color)(this["PlotterCPUKernelColor"]));
            }
            set {
                this["PlotterCPUKernelColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color PlotterCPUUserColor {
            get {
                return ((global::System.Drawing.Color)(this["PlotterCPUUserColor"]));
            }
            set {
                this["PlotterCPUUserColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Orange")]
        public global::System.Drawing.Color PlotterMemoryPrivateColor {
            get {
                return ((global::System.Drawing.Color)(this["PlotterMemoryPrivateColor"]));
            }
            set {
                this["PlotterMemoryPrivateColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cyan")]
        public global::System.Drawing.Color PlotterMemoryWSColor {
            get {
                return ((global::System.Drawing.Color)(this["PlotterMemoryWSColor"]));
            }
            set {
                this["PlotterMemoryWSColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yellow")]
        public global::System.Drawing.Color PlotterIOROColor {
            get {
                return ((global::System.Drawing.Color)(this["PlotterIOROColor"]));
            }
            set {
                this["PlotterIOROColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkViolet")]
        public global::System.Drawing.Color PlotterIOWColor {
            get {
                return ((global::System.Drawing.Color)(this["PlotterIOWColor"]));
            }
            set {
                this["PlotterIOWColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Peru")]
        public global::System.Drawing.Color ColorJobProcesses {
            get {
                return ((global::System.Drawing.Color)(this["ColorJobProcesses"]));
            }
            set {
                this["ColorJobProcesses"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowOneGraphPerCPU {
            get {
                return ((bool)(this["ShowOneGraphPerCPU"]));
            }
            set {
                this["ShowOneGraphPerCPU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int UnitSpecifier {
            get {
                return ((int)(this["UnitSpecifier"]));
            }
            set {
                this["UnitSpecifier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("222, 255, 0")]
        public global::System.Drawing.Color ColorDotNetProcesses {
            get {
                return ((global::System.Drawing.Color)(this["ColorDotNetProcesses"]));
            }
            set {
                this["ColorDotNetProcesses"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DeepPink")]
        public global::System.Drawing.Color ColorPackedProcesses {
            get {
                return ((global::System.Drawing.Color)(this["ColorPackedProcesses"]));
            }
            set {
                this["ColorPackedProcesses"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool VerifySignatures {
            get {
                return ((bool)(this["VerifySignatures"]));
            }
            set {
                this["VerifySignatures"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NetworkListViewColumns {
            get {
                return ((string)(this["NetworkListViewColumns"]));
            }
            set {
                this["NetworkListViewColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableKPH {
            get {
                return ((bool)(this["EnableKPH"]));
            }
            set {
                this["EnableKPH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StartHidden {
            get {
                return ((bool)(this["StartHidden"]));
            }
            set {
                this["StartHidden"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>audiodg.exe</string>
  <string>csrss.exe</string>
  <string>dwm.exe</string>
  <string>explorer.exe</string>
  <string>lsass.exe</string>
  <string>lsm.exe</string>
  <string>ntkrnlpa.exe</string>
  <string>ntoskrnl.exe</string>
  <string>procexp.exe</string>
  <string>rundll32.exe</string>
  <string>services.exe</string>
  <string>smss.exe</string>
  <string>spoolsv.exe</string>
  <string>svchost.exe</string>
  <string>taskeng.exe</string>
  <string>taskmgr.exe</string>
  <string>wininit.exe</string>
  <string>winlogon.exe</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ImposterNames {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ImposterNames"]));
            }
            set {
                this["ImposterNames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif, 8.25pt")]
        public global::System.Drawing.Font Font {
            get {
                return ((global::System.Drawing.Font)(this["Font"]));
            }
            set {
                this["Font"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HideHandlesWithNoName {
            get {
                return ((bool)(this["HideHandlesWithNoName"]));
            }
            set {
                this["HideHandlesWithNoName"] = value;
            }
        }
    }
}
