//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessHacker.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int RefreshInterval {
            get {
                return ((int)(this["RefreshInterval"]));
            }
            set {
                this["RefreshInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("820, 549")]
        public global::System.Drawing.Size WindowSize {
            get {
                return ((global::System.Drawing.Size)(this["WindowSize"]));
            }
            set {
                this["WindowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200, 200")]
        public global::System.Drawing.Point WindowLocation {
            get {
                return ((global::System.Drawing.Point)(this["WindowLocation"]));
            }
            set {
                this["WindowLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("355")]
        public int SplitterDistance {
            get {
                return ((int)(this["SplitterDistance"]));
            }
            set {
                this["SplitterDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState WindowState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["WindowState"]));
            }
            set {
                this["WindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DebugMem {
            get {
                return ((bool)(this["DebugMem"]));
            }
            set {
                this["DebugMem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("&Literal Search...")]
        public string SearchType {
            get {
                return ((string)(this["SearchType"]));
            }
            set {
                this["SearchType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowAccountDomains {
            get {
                return ((bool)(this["ShowAccountDomains"]));
            }
            set {
                this["ShowAccountDomains"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WarnDangerous {
            get {
                return ((bool)(this["WarnDangerous"]));
            }
            set {
                this["WarnDangerous"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ProcessTreeColumns {
            get {
                return ((string)(this["ProcessTreeColumns"]));
            }
            set {
                this["ProcessTreeColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ThreadListViewColumns {
            get {
                return ((string)(this["ThreadListViewColumns"]));
            }
            set {
                this["ThreadListViewColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("504, 482")]
        public global::System.Drawing.Size ResultsWindowSize {
            get {
                return ((global::System.Drawing.Size)(this["ResultsWindowSize"]));
            }
            set {
                this["ResultsWindowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ModuleListViewColumns {
            get {
                return ((string)(this["ModuleListViewColumns"]));
            }
            set {
                this["ModuleListViewColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MemoryListViewColumns {
            get {
                return ((string)(this["MemoryListViewColumns"]));
            }
            set {
                this["MemoryListViewColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("791, 503")]
        public global::System.Drawing.Size MemoryWindowSize {
            get {
                return ((global::System.Drawing.Size)(this["MemoryWindowSize"]));
            }
            set {
                this["MemoryWindowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ResultsListViewColumns {
            get {
                return ((string)(this["ResultsListViewColumns"]));
            }
            set {
                this["ResultsListViewColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tabProcesses")]
        public string SelectedTab {
            get {
                return ((string)(this["SelectedTab"]));
            }
            set {
                this["SelectedTab"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PrivilegeListColumns {
            get {
                return ((string)(this["PrivilegeListColumns"]));
            }
            set {
                this["PrivilegeListColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GroupListColumns {
            get {
                return ((string)(this["GroupListColumns"]));
            }
            set {
                this["GroupListColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("481, 468")]
        public global::System.Drawing.Size TokenWindowSize {
            get {
                return ((global::System.Drawing.Size)(this["TokenWindowSize"]));
            }
            set {
                this["TokenWindowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("439, 413")]
        public global::System.Drawing.Size PEWindowSize {
            get {
                return ((global::System.Drawing.Size)(this["PEWindowSize"]));
            }
            set {
                this["PEWindowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PECOFFHColumns {
            get {
                return ((string)(this["PECOFFHColumns"]));
            }
            set {
                this["PECOFFHColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PECOFFOHColumns {
            get {
                return ((string)(this["PECOFFOHColumns"]));
            }
            set {
                this["PECOFFOHColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PEImageDataColumns {
            get {
                return ((string)(this["PEImageDataColumns"]));
            }
            set {
                this["PEImageDataColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PESectionsColumns {
            get {
                return ((string)(this["PESectionsColumns"]));
            }
            set {
                this["PESectionsColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PEExportsColumns {
            get {
                return ((string)(this["PEExportsColumns"]));
            }
            set {
                this["PEExportsColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PEImportsColumns {
            get {
                return ((string)(this["PEImportsColumns"]));
            }
            set {
                this["PEImportsColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.google.com/search?q=%s")]
        public string SearchEngine {
            get {
                return ((string)(this["SearchEngine"]));
            }
            set {
                this["SearchEngine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("170, 255, 170")]
        public global::System.Drawing.Color ColorNewProcesses {
            get {
                return ((global::System.Drawing.Color)(this["ColorNewProcesses"]));
            }
            set {
                this["ColorNewProcesses"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 170, 170")]
        public global::System.Drawing.Color ColorRemovedProcesses {
            get {
                return ((global::System.Drawing.Color)(this["ColorRemovedProcesses"]));
            }
            set {
                this["ColorRemovedProcesses"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 255, 170")]
        public global::System.Drawing.Color ColorOwnProcesses {
            get {
                return ((global::System.Drawing.Color)(this["ColorOwnProcesses"]));
            }
            set {
                this["ColorOwnProcesses"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 85, 85")]
        public global::System.Drawing.Color ColorHighlight {
            get {
                return ((global::System.Drawing.Color)(this["ColorHighlight"]));
            }
            set {
                this["ColorHighlight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("170, 204, 255")]
        public global::System.Drawing.Color ColorSystemProcesses {
            get {
                return ((global::System.Drawing.Color)(this["ColorSystemProcesses"]));
            }
            set {
                this["ColorSystemProcesses"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int HighlightingDuration {
            get {
                return ((int)(this["HighlightingDuration"]));
            }
            set {
                this["HighlightingDuration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AlwaysOnTop {
            get {
                return ((bool)(this["AlwaysOnTop"]));
            }
            set {
                this["AlwaysOnTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("415, 503")]
        public global::System.Drawing.Size ThreadWindowSize {
            get {
                return ((global::System.Drawing.Size)(this["ThreadWindowSize"]));
            }
            set {
                this["ThreadWindowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CallStackColumns {
            get {
                return ((string)(this["CallStackColumns"]));
            }
            set {
                this["CallStackColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseToolhelpModules {
            get {
                return ((bool)(this["UseToolhelpModules"]));
            }
            set {
                this["UseToolhelpModules"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NewProcesses {
            get {
                return ((bool)(this["NewProcesses"]));
            }
            set {
                this["NewProcesses"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TerminatedProcesses {
            get {
                return ((bool)(this["TerminatedProcesses"]));
            }
            set {
                this["TerminatedProcesses"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool NewServices {
            get {
                return ((bool)(this["NewServices"]));
            }
            set {
                this["NewServices"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool StartedServices {
            get {
                return ((bool)(this["StartedServices"]));
            }
            set {
                this["StartedServices"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool StoppedServices {
            get {
                return ((bool)(this["StoppedServices"]));
            }
            set {
                this["StoppedServices"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DeletedServices {
            get {
                return ((bool)(this["DeletedServices"]));
            }
            set {
                this["DeletedServices"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowIcon {
            get {
                return ((bool)(this["ShowIcon"]));
            }
            set {
                this["ShowIcon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HideHandlesNoName {
            get {
                return ((bool)(this["HideHandlesNoName"]));
            }
            set {
                this["HideHandlesNoName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ServiceListViewColumns {
            get {
                return ((string)(this["ServiceListViewColumns"]));
            }
            set {
                this["ServiceListViewColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HandleListViewColumns {
            get {
                return ((string)(this["HandleListViewColumns"]));
            }
            set {
                this["HandleListViewColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FilterHandleListViewColumns {
            get {
                return ((string)(this["FilterHandleListViewColumns"]));
            }
            set {
                this["FilterHandleListViewColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("554, 463")]
        public global::System.Drawing.Size FilterHandleWindowSize {
            get {
                return ((global::System.Drawing.Size)(this["FilterHandleWindowSize"]));
            }
            set {
                this["FilterHandleWindowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("204, 187, 255")]
        public global::System.Drawing.Color ColorBeingDebugged {
            get {
                return ((global::System.Drawing.Color)(this["ColorBeingDebugged"]));
            }
            set {
                this["ColorBeingDebugged"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("204, 255, 255")]
        public global::System.Drawing.Color ColorServiceProcesses {
            get {
                return ((global::System.Drawing.Color)(this["ColorServiceProcesses"]));
            }
            set {
                this["ColorServiceProcesses"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PromptBoxText {
            get {
                return ((string)(this["PromptBoxText"]));
            }
            set {
                this["PromptBoxText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RunAsUsername {
            get {
                return ((string)(this["RunAsUsername"]));
            }
            set {
                this["RunAsUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RunAsCommand {
            get {
                return ((string)(this["RunAsCommand"]));
            }
            set {
                this["RunAsCommand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tabPrivileges")]
        public string TokenWindowTab {
            get {
                return ((string)(this["TokenWindowTab"]));
            }
            set {
                this["TokenWindowTab"] = value;
            }
        }
    }
}
